// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmbDXKbHa4ex5RDk9dJCITjmlQai4nI6k',
    appId: '1:192511537789:web:2bb333cdd0532e31f47714',
    messagingSenderId: '192511537789',
    projectId: 'ontrend-db',
    authDomain: 'ontrend-db.firebaseapp.com',
    storageBucket: 'ontrend-db.appspot.com',
    measurementId: 'G-K6KBX0PF4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3aMrrW0c68KIOwHFc-w-MyMxE-MvIBLo',
    appId: '1:192511537789:android:28d4ddef7465a0faf47714',
    messagingSenderId: '192511537789',
    projectId: 'ontrend-db',
    storageBucket: 'ontrend-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXCdL4BaZ1lioNwIOObug-eat1AulDCsw',
    appId: '1:192511537789:ios:7428d42d527cc743f47714',
    messagingSenderId: '192511537789',
    projectId: 'ontrend-db',
    storageBucket: 'ontrend-db.appspot.com',
    iosClientId: '192511537789-ol7ihhuct6jdggp5orue6ja8fhumbtqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ontrendFoodAndECommerce',
  );

}