import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Choose a language': 'Choose a language',
          'hello': 'HELLO WORLD',
          'message': "WELCOME TO APP",
          'My Profile': 'My Profile',
          '*Name...': 'Name',
          '*Email...': 'Email',
          'Nationality': 'Nationality',
          'My Orders': 'My Orders',
          'Help': 'Help',
          'Contact Us': 'Contact Us',
          'Log Out': 'Log Out',
          'English': 'English',
          'Arabic': 'عربي',
          'Our Services': 'Our Services',
          'Biryani, Burger, Ice Cream...': 'Biryani, Burger, Ice Cream...',
          'E-Store': 'E-Store',
          'Food': 'Food',
          'Groceries': 'Groceries',
          'Best Sellers': 'Best Sellers',
          'Categories': 'Categories',
          'Restaurants to explore': 'Restaurants to explore',
          'Vegetables, fruits...': 'Vegetables, fruits...',
          "Trending on OnTrend": "Trending on OnTrend",
          "Store to explore": "Store to explore",
          'Fresh Vegetables': 'Fresh Vegetables',
          "Payment Options": "Payment Options",
          "Pay on Delivery": "Pay on Delivery",
          "Save any pay via cards": "Save any pay via cards",
          "Add New Card": "Add New Card",
          "Notification": "Notification",
          "Welcome back!": "Welcome back!",
          "Email ID": "Email ID",
          "Email is required": "Email is required",
          "Email must be 6 Letter": "Email must be 6 Letter",
          "Password": "Password",
          'Password is required': 'Password is required',
          "Password must be 8 Letter": "Password must be 8 Letter",
          "Forgot Password?": "Forgot Password?",
          "Login": "Login",
          "Don’t have an account?": "Don’t have an account?",
          "Sign Up": "Sign Up",
          "Register": "Register",
          "Just a few things to get started":
              "Just a few things to get started",
          "First Name*": "First Name*",
          'Please enter your first name': 'Please enter your first name',
          "Last Name*": "Last Name*",
          'Please enter your last name': 'Please enter your last name',
          'Change': 'Change',
          "Create Account": "Create Account",
          'Please enter your password': 'Please enter your password',
          "Password*": "Password*",
          'Please enter your number': 'Please enter your number',
          "Mobile Number*": "Mobile Number*",
          'Please select your Nationality': 'Please select your Nationality',
          'Please enter a valid email': 'Please enter a valid email',
          'Please enter your email': 'Please enter your email',
          "Email*": "Email*",
          "Verify Your Number": "Verify Your Number",
          "You will receive a 4 digit OTP\nto your phone number.":
              "You will receive a 4 digit OTP\nto your phone number.",
          "Didn't receive code? ": "Didn't receive code? ",
          "Resend": "Resend",
          "Verify": "Verify",
          'Error': 'Error',
          'User already exists.': 'User already exists.',
          'Invalid OTP.': 'Invalid OTP.',
          "Email ID or Phone No": "Email ID or Phone No",
          "You will receive your password on your\nregistered email or phone":
              "You will receive your password on your\nregistered email or phone",
          "Forgot Password": "Forgot Password",
          "Send": "Send",
          'Password reset email sent successfully':
              'Password reset email sent successfully',
          'Do you have an account?': 'Do you have an account?',
          'Select Nationality': 'Select Nationality',
          'Start typing to search': 'Start typing to search',
          "Something went wrong": "Something went wrong",
          "Item not in cart": "Item not in cart",
          "Add more items": "Add more items",
          "Add cooking requests": "Add cooking requests",
          "Place Order": "Place Order",
          "Add": "Add",
          "Your Order Has Been Placed Successfully":
              "Your Order Has Been Placed Successfully",
          "OMR": "OMR",
          "Home": "Home",
          "Profile": "Profile",
          "Search...": "Search...",
          "No Vendor Available": "No Vendor Available",
          "Offers & Benefits": "Offers & Benefits",
          "Bill Details": "Bill Details",
          'Item total': 'Item total',
          'Delivery fee': 'Delivery fee',
          'Total amount': 'Total amount',
          'Add to Cart': 'Add to Cart',
          "History": "History",
          "Ongoing": "Ongoing",
          "Sheduled": "Sheduled",
          "Type a coupon code here": "Type a coupon code here",
          "Apply": "Apply",
          "Terms & Conditions": "Terms & Conditions",
          'Item added to cart': 'Item added to cart',
          "Edit Address Title": "Edit Address Title",
          "Enter new title": "Enter new title",
          "Cancel": "Cancel",
          "Save": "Save",
          'Service fee': 'Service fee',
          "Vendor not found": "Vendor not found",
          "Pizza, Pastas, Desserts": "Pizza, Pastas, Desserts",
          "Delivery time": "Delivery time",
          "Delivery by": "Delivery by",
          "OnTrend": "OnTrend",
          "No items found": "No items found",
          "Nearby Restaurants": "Nearby Restaurants",
          "Search for area, street name...": "Search for area, street name...",
          "Select Location": "Select Location",
          "Use my current location": "Use my current location",
          "Add location from map": "Add location from map",
          "SAVED ADDRESSES": "SAVED ADDRESSES",
          "Custom Location": "Custom Location",
          "Search Result": "Search Result",
          "No items found in the cart.": "No items found in the cart.",
          "Add Items to Cart": "Add Items to Cart",
          "Location Required": "Location Required",
          "You haven't selected your location":
              "You haven't selected your location",
          "Available Voulchers": "Available Voulchers",
          "Add notes": "Add notes",
          "All": "All",
          "E - Cart": "E - Cart",
          "Rewards: ": "Rewards: ",
          "Points": "Points",
          "Stores to Explore": "Stores to Explore",
          "min": "min",
          "mins": "mins",
          'View Cart': 'View Cart',
          "Items in Cart:": "Items in Cart:",
          'No image available': 'No image available',
          "km away": "km away",
          "Past Orders": "Past Orders",
          'No orders found': 'No orders found',
          "No Image Available": "No Image Available",
          'Order data is null': 'Order data is null',
          'Error parsing order data': 'Error parsing order data',
          "is your delivery hero for\ntoday.":
              "is your delivery hero for\ntoday.",
          "Waiting for acceptance": "Waiting for acceptance",
          "Your delivery hero details will\nappear here once accepted.":
              "Your delivery hero details will\nappear here once accepted.",
          "No Notification": "No Notification",
          "Pending": "Pending",
          "Processing": "Processing",
          "Ready": "Ready",
          "Picked Up": "Picked Up",
          "Delivered": "Delivered",
          "Order Details": "Order Details",
          "Order ID": "Order ID",
          "Order Total": "Order Total",
          "Payment Method": "Payment Method",
          "Cash": "Cash",
          "Order Menu": "Order Menu",
          "Distance:": "Distance:",
          "Estimated Delivery Time:": "Estimated Delivery Time:",
          "km": "km",
          "No Nearby Restaurants": "No Nearby Restaurants",
          "No Nearby Stores": "No Nearby Stores",
          "Up to 40% Off": "Up to 40% Off",
          'LogOut ?': 'LogOut ?',
          'Are you sure you want to log out?':
              'Are you sure you want to log out?',
        },
        //'hi_IN': {'hello': "नमस्ते दुनिया", 'message': "ऐप में आपका स्वागत है"},
        'ar_OM': {
          'Choose a language': 'اختر لغة',
          'hello': "مرحبا بالعالم",
          'message': "مرحبا بكم في التطبيق",
          'My Profile': 'ملفي الشخصي',
          '*Name...': 'الاسم',
          '*Email...': 'البريد الإلكتروني',
          'Nationality': 'الجنسية',
          'My Orders': 'طلباتي',
          'Help': "مساعدة",
          'Contact Us': 'اتصل بنا',
          'Log Out': 'تسجيل الخروج',
          'English': 'الإنجليزية',
          'Arabic': 'عربي',
          'Our Services': 'خدماتنا',
          'Biryani, Burger, Ice Cream...': 'مثال: الفاكهة، خضروات.. الخ',
          'E-Store': 'المتجر الإلكتروني',
          'Food': 'الأطعمة',
          'Groceries': 'البقالة',
          'Best Sellers': 'أفضل البائعين',
          'Categories': 'الفئات',
          'Restaurants to explore': 'مطاعم مقترحة',
          'Vegetables, fruits...': 'الفاكهة خضروات ',
          "Trending on OnTrend": "الشائع",
          "Store to explore": 'متجر للاستكشاف',
          'Fresh Vegetables': 'الخضروات الطازجة',
          "Payment Options": "خيارات الدفع",
          "Pay on Delivery": "الدفع عند الاستلام",
          "Save any pay via cards": "حفظ أي دفع عن طريق البطاقات",
          "Add New Card": "إضافة بطاقة جديدة",
          "Notification": "إشعار",
          "Welcome back!": "مرحبًا بعودتك!",
          "Email ID": "بريد إلكتروني ",
          "Email is required": "البريد الالكتروني مطلوب",
          "Email must be 6 Letter": "البريد الإلكتروني يجب أن يتكون من 6 أحرف",
          "Password": "كلمة المرور",
          'Password is required': 'كلمة المرور مطلوبة',
          "Password must be 8 Letter": "كلمة المرور يجب أن تكون 8 أحرف",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Login": "تسجيل الدخول",
          "Don’t have an account?": "ليس لديك حساب؟",
          "Sign Up": "اشتراك",
          "Register": "يسجل",
          "Just a few things to get started": "فقط بعض الأشياء للبدء",
          "First Name*": "الاسم الأول*",
          'Please enter your first name': 'يرجى ادخال الاسم الاول',
          "Last Name*": "اسم العائلة*",
          'Please enter your last name': "الرجاء إدخال اسمك الأخير",
          'Change': 'تغيير',
          "Create Account": "إنشاء حساب",
          'Please enter your password': 'من فضلك أدخل رقمك السري',
          "Password*": "كلمة المرور*",
          'Please enter your number': "الرجاء إدخال رقمك",
          "Mobile Number*": "رقم الهاتف المحمول*",
          'Please select your Nationality': "الرجاء تحديد جنسيتك",
          'Please enter a valid email': 'يرجى إدخال البريد الإلكتروني الصحيح',
          'Please enter your email': 'رجاءا أدخل بريدك الإلكتروني',
          "Email*": "بريد إلكتروني*",
          "Verify Your Number": "التحقق من رقمك",
          "You will receive a 4 digit OTP\nto your phone number.":
              "ستتلقى كلمة مرور لمرة واحدة (OTP) مكونة من 4 أرقام\nعلى رقم هاتفك.",
          "Didn't receive code? ": "لم تتلق الرمز؟",
          "Resend": "إعادة إرسال",
          "Verify": "يؤكد",
          'Error': 'خطأ',
          'User already exists.': 'المستخدم موجود اصلا.',
          'Invalid OTP.': "كلمة المرور لمرة واحدة غير صالحة.",
          "Email ID or Phone No": "معرف البريد الإلكتروني أو رقم الهاتف",
          "You will receive your password on your\nregistered email or phone":
              "سوف تتلقى كلمة المرور الخاصة بك على\nالبريد الإلكتروني أو الهاتف المسجل",
          "Forgot Password": "هل نسيت كلمة السر؟",
          "Send": "يرسل",
          'Password reset email sent successfully':
              "تم إرسال البريد الإلكتروني لإعادة تعيين كلمة المرور بنجاح",
          'Do you have an account?': 'هل لديك حساب؟',
          'Select Nationality': "اختر الجنسية",
          'Start typing to search': "ابدأ الكتابة للبحث",
          "Something went wrong": "هناك خطأ ما",
          "Item not in cart": "العنصر ليس في سلة التسوق",
          "Add more items": "إضافة المزيد من العناصر",
          "Add cooking requests": "إضافة طلبات الطبخ",
          "Place Order": "تنفيذ الطلب",
          "Add": "اضافة",
          "Your Order Has Been Placed Successfully": "تم تقديم طلبك بنجاح",
          "OMR": "ريال",
          "Home": "الرئيسية",
          "Profile": "حسابك",
          "Search...": "يبحث...",
          "No Vendor Available": "لا يوجد بائع",
          "Offers & Benefits": "العروض والمزايا",
          "Bill Details": "تفاصيل الفاتورة",
          'Item total': 'مجموع الاشياء',
          'Delivery fee': 'رسوم التوصيل',
          'Service fee': 'رسوم الخدمة',
          'Total amount': 'المبلغ الإجمالي',
          'Add to Cart': 'أضف إلى السلة',
          "History": "تاريخ",
          "Ongoing": "جاري التنفيذ",
          "Sheduled": "المقرر",
          "Type a coupon code here": "اكتب رمز القسيمة هنا",
          "Apply": "استخدم ",
          "Terms & Conditions": "الأحكام والشروط",
          'Item added to cart': "تم إضافة السلعة إلى سلة التسوق",
          "Edit Address Title": "اضف العنوان",
          "Enter new title": "أدخل عنوانًا جديدًا",
          "Cancel": "إلغاء ",
          "Save": "حفظ",
          "Vendor not found": "لم يتم العثور على البائع",
          "Pizza, Pastas, Desserts": "البيتزا والمعكرونة والحلويات",
          "Delivery time": "وقت التوصيل",
          "Delivery by": "التوصيل بواسطة",
          "OnTrend": "اونتريند",
          "No items found": "لم يتم العثور على العناصر",
          "Nearby Restaurants": "مطاعم بالقرب منك",
          "Search for area, street name...": "البحث عن المنطقة، اسم الشارع...",
          "Select Location": "اختر موقعا",
          "Use my current location": "استخدام موقعي الحالي",
          "Add location from map": "إضافة الموقع من الخريطة",
          "SAVED ADDRESSES": "العناوين المحفوظة",
          "Custom Location": "الموقع",
          "Search Result": "نتيجة البحث",
          "No items found in the cart.": "لا توجد طلبات في السلة",
          "Add Items to Cart": "اضافة طلبات الى السلة",
          "Location Required": "الموقع مطلوب",
          "You haven't selected your location": "لم تقم بتحديد موقعك",
          "Available Voulchers": "القسيمة المتاحة",
          "Add notes": "اضافة ملاحظة",
          "All": "الجميع",
          "E - Cart": "العربة الإلكترونية",
          "Rewards: ": "المكافآت ",
          "Points": "نقاط",
          "Stores to Explore": "المحلات المقترحة",
          "mins": "دقائق",
          "min": "دقائق",
          'View Cart': "اطلع على سلتك ",
          "Items in Cart:": "طلباتك في السلة",
          'No image available': 'لا توجد صورة',
          "km away": "على بعد كيلومتر",
          "Past Orders": "الأوامر السابقة",
          'No orders found': 'لم يتم العثور على أية طلبات',
          "No Image Available": "لا توجد صورة",
          'Order data is null': "بيانات الطلب فارغة",
          'Error parsing order data': "حدث خطأ أثناء تحليل بيانات الطلب",
          "is your delivery hero for\ntoday.": "هو بطل التوصيل اليوم.",
          "Waiting for acceptance": "في انتظار القبول",
          "Your delivery hero details will\nappear here once accepted.":
              "سوف تظهر تفاصيل التسليم الرئيسي هنا بمجرد قبولها.",
          "No Notification": "لا يوجد إشعارات",
          "Pending": "قيد الانتظار",
          "Processing": "يعالج",
          "Ready": "مستعد",
          "Picked Up": "التقطت",
          "Delivered": "تم التوصيل",
          "Order Details": "تفاصيل الطلب",
          "Order ID": "رقم التعريف الخاص بالطلب",
          "Order Total": "الطلب الكلي",
          "Payment Method": "طريقة الدفع او السداد",
          "Cash": "نقدي",
          "Order Menu": "قائمة الطلب",
          "Distance:": "مسافة:",
          "Estimated Delivery Time:": "يقدر وقت التسليم:",
          "km": "الكيلومتر",
          "No Nearby Restaurants": "لا توجد مطاعم قريبة",
          "No Nearby Stores": "لا توجد متاجر قريبة",
          "Up to 40% Off": "تخفيض يصل إلى ٤٠٪",
          'LogOut ?': 'تسجيل خروج ؟',
          'Are you sure you want to log out?':
              "هل أنت متأكد أنك تريد تسجيل الخروج؟",
        }
      };
}
