import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Choose a language': 'Choose a language',
          'hello': 'HELLO WORLD',
          'message': "WELCOME TO APP",
          'My Profile': 'My Profile',
          'Name': 'Name',
          'Email': 'Email',
          'Nationality': 'Nationality',
          'My Orders': 'My Orders',
          'Help': 'Help',
          'Contact Us': 'Contact Us',
          'Log Out': 'Log Out',
          'English': 'English',
          'Arabic': 'عربي',
          'Our Services': 'Our Services',
          'Biryani, Burger, Ice Cream...': 'Biryani, Burger, Ice Cream...',
          'E-Store': 'E-Store',
          'Food': 'Food',
          'Groceries': 'Groceries',
          'Best Sellers': 'Best Sellers',
          'Categories': 'Categories',
          'Restaurants to explore': 'Restaurants to explore',
          'Vegetables, fruits...': 'Vegetables, fruits...',
          "Trending on Ontrend": "Trending on Ontrend",
          "Store to explore": "Store to explore",
          'Fresh Vegetables': 'Fresh Vegetables',
          "Payment Options": "Payment Options",
          "Pay on Delivery": "Pay on Delivery",
          "Save any pay via cards": "Save any pay via cards",
          "Add New Card": "Add New Card",
          "Notification": "Notification",
        },
        //'hi_IN': {'hello': "नमस्ते दुनिया", 'message': "ऐप में आपका स्वागत है"},
        'ar_OM': {
          'Choose a language': 'اختر لغة',
          'hello': "مرحبا بالعالم",
          'message': "مرحبا بكم في التطبيق",
          'My Profile': 'ملفي الشخصي',
          'Name': 'الاسم',
          'Email': 'البريد الإلكتروني',
          'Nationality': 'الجنسية',
          'My Orders': 'طلباتي',
          'Help': 'مساعدة',
          'Contact Us': 'اتصل بنا',
          'Log Out': 'تسجيل الخروج',
          'English': 'الإنجليزية',
          'Arabic': 'عربي',
          'Our Services': 'خدماتنا',
          'Biryani, Burger, Ice Cream...': 'برياني، برجر، آيس كريم',
          'E-Store': 'المتجر الإلكتروني',
          'Food': 'طعام',
          'Groceries': 'البقالة',
          'Best Sellers': 'أفضل البائعين',
          'Categories': 'فئات',
          'Restaurants to explore': 'مطاعم للاستكشاف',
          'Vegetables, fruits...': 'الفاكهة خضروات ',
          "Trending on Ontrend": "الشائع",
          "Store to explore": 'متجر للاستكشاف',
          'Fresh Vegetables': 'الخضروات الطازجة',
          "Payment Options": "خيارات الدفع",
          "Pay on Delivery": "الدفع عند الاستلام",
          "Save any pay via cards": "حفظ أي دفع عن طريق البطاقات",
          "Add New Card": "إضافة بطاقة جديدة",
          "Notification": "إشعار",
        }
      };
}
